Feature/post
headshotMoufu/headshotMoufu pull request #22
Opened 2021-12-03 07:27 UTC by wackhack46

これであってますか？

2021-12-03 07:53 UTC, handojisan requested changes
お疲れ様！
コードからかざとの頑張りを感じました😊
直すところを書いたので、確認お願いします！

2021-12-03 07:53 UTC, handojisan commented on src/views/Upload.vue
> +<script></script>
script タグは二ついらないので、これは消そう。
見た感じ、vueくんがこっちのscriptタグのみ認識しているっぽく、それが
```
Invalid handler for event "click": got undefined
```
のエラー原因っぽい👀

2021-12-03 07:53 UTC, handojisan commented on src/firebase.js
> +export const db = getFirestore(app)
これでも動くんだけど、[firebaseの公式ドキュメント](https://firebase.google.com/docs/firestore/quickstart?hl=ja#initialize)に合わせて、
`export const db = getFirestore()`

にしよう

2021-12-03 07:53 UTC, handojisan commented on src/views/Upload.vue
> +      <button type="submit" class="submit" id="submit" @click="postMassage">
これはさっき指摘した通り、
`postMessage`にしよう

2021-12-03 07:53 UTC, handojisan commented on src/views/Upload.vue
> +import { doc, getDoc } from "firebase/firestore"
これ、`firebase/firestore` から一気にimport できる。

```
import { collection, addDoc, doc, getDoc } from "firebase/firestore"
```

こっちの方が分かりやすいと思う！

2021-12-03 07:53 UTC, handojisan commented on src/views/Upload.vue
> +import { doc, getDoc } from "firebase/firestore"
で、これなんだけど、結論から言うと
```
import { collection, addDoc, getDocs } from "firebase/firestore"
```
でOK。
今回は、`doc` も `getDoc` も使わないです

2021-12-03 07:53 UTC, handojisan commented on src/views/Upload.vue
> +      this.masseages.push(docRef)
スペルミスw
```
this.message.push(docRef)
```

2021-12-03 07:53 UTC, handojisan commented on src/views/Upload.vue
> +    const docRef = doc(db, "messages")
単体のdata読み取りと、複数dataの読み取りを混同している感じがする！

今回は全てのデータを取ってきたいので、
[Cloud Firestore でデータを取得する](https://firebase.google.com/docs/firestore/query-data/get-data?hl=ja) の下の方にある「コレクションのすべてのドキュメントを取得する」が参考になるかな。

```
const querySnapshot = await getDocs(collection(db, "users"));
querySnapshot.forEach((doc) => {
  console.log(`${doc.id} => ${doc.data()}`);
});
```

これを今回の場合に当てはめてみて欲しい！

2021-12-03 08:08 UTC, junseinagao commented on src/views/Upload.vue
> +      <button type="submit" class="submit" id="submit" @click="postMassage">
@wackhack46 

このボタン formと組み合わせてるなら submitの挙動をpreventする必要があるから気を付けてね

https://www.kimullaa.com/entry/2019/12/01/140912

2021-12-03 09:07 UTC, wackhack46 commented
一通り修正しましたが、投稿ページの送信を押すと４つエラーが出てきます。https://firebase.google.com/docs/reference/js/firestore_.collectionreferenceのページを参考にしましたが、エラー消せませんでした

以下consoleのエラーです。

vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in created hook (Promise/async): "FirebaseError: [code=invalid-argument]: Expected type 'Aa', but it was: a custom en object"

found in

---> <Upload> at src/views/Upload.vue
       <App> at src/App.vue
         <Root>
warn @ vue.runtime.esm.js?2b0e:619
vue.runtime.esm.js?2b0e:1897 FirebaseError: Expected type 'Aa', but it was: a custom en object
    at ga (index.esm2017.js?0829:14644)
    at lh (index.esm2017.js?0829:17415)
    at _callee2$ (Upload.vue?b679:56)
    at tryCatch (runtime.js?96cf:63)
    at Generator.invoke [as _invoke] (runtime.js?96cf:294)
    at Generator.eval [as next] (runtime.js?96cf:119)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
    at _next (asyncToGenerator.js?1da1:25)
    at eval (asyncToGenerator.js?1da1:32)
    at new Promise (<anonymous>)
logError @ vue.runtime.esm.js?2b0e:1897
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in v-on handler (Promise/async): "FirebaseError: [code=invalid-argument]: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore"

found in

---> <Upload> at src/views/Upload.vue
       <App> at src/App.vue
         <Root>
warn @ vue.runtime.esm.js?2b0e:619
vue.runtime.esm.js?2b0e:1897 FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
    at ba (index.esm2017.js?0829:14943)
    at _callee$ (Upload.vue?b679:39)
    at tryCatch (runtime.js?96cf:63)
    at Generator.invoke [as _invoke] (runtime.js?96cf:294)
    at Generator.eval [as next] (runtime.js?96cf:119)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
    at _next (asyncToGenerator.js?1da1:25)
    at eval (asyncToGenerator.js?1da1:32)
    at new Promise (<anonymous>)
    at eval (asyncToGenerator.js?1da1:21)

2021-12-03 13:22 UTC, handojisan commented
ごめん、今のコード送って貰っていい？

2021-12-03 15:56 UTC, handojisan commented
ごめん時間かかったけど、分かった！笑

確かに、createdに書いてあるやつも間違っているんだけど、実は正しく書いたとしても間違いだよって言ってくる😅
そして、`postMessage`に書いてあるのは、ちゃんとあってる！

でも、実際動いていない……
なんで？🤔 って僕もなりました。。。

実は、firebase.js でこういうコードになっていました👀
```
import { getFirestore } from "firebase/firestore/lite"
```

`firebase/firestore/lite`は、`firebase/firestore` とはまたちょっと違うやつです。
これを使う場合は全てのファイルで`firebase/firestore/lite` と統一させなきゃいけないようです😇

> `firebase/firestore/lite` は、`firebase/firestore` と比べて、色々機能が制約されている代わりに軽い、というイメージで大丈夫です。詳しくは[Cloud Firestore Lite Web SDK](https://firebase.google.com/docs/firestore/solutions/firestore-lite) を読んでみてね。

今回は機能を制約されたら困るし、軽いとは言っても実はパフォーマンスについてもどっちが有利か微妙なので、普通のバージョンを使いましょう！
ということで、全ての場所で`"firebase/firestore"`を使うように変更しよう！

具体的には、firebase.jsの該当の場所を
```
import { getFirestore } from "firebase/firestore"
```

に書き換えればOK！

2021-12-04 17:47 UTC, wackhack46 commented
コメント：これは見るべき！！をクリックしたらyoutubeの動画に飛べます　（うんちもれたはgeekの教材に飛びます　その他は何もリンクを入れてないので動きません）

2021-12-04 17:50 UTC, darse73 commented
やったー！

2021-12-05 04:41 UTC, handojisan commented on src/views/Upload.vue
> +      <button type="submit" class="submit" id="submit" @click="postMassage">
このじゅんぱいの言ってるやつ、修正お願いします！

2021-12-10 14:00 UTC, merged